config/routes.rb
Project::Application.routes.draw do
  devise_for :users

  resources :aplicacions 

  get "tesina/paginaPrincipal"

end

app/models/ability.rb
class Ability  
 include CanCan::Ability  
   
   def initialize(user)  
     can :read, :all
   end  
 end  

app/models/aplicacion.rb
class Aplicacion < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base


  ROLES = %w[admin visor]

  # Include default devise modules. Others available are:
  # :token_authenticatable, :lockable, :timeoutable and :activatable
  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :role_mask

  def roles=(roles)
    self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.sum
  end

  def roles
    ROLES.reject do |r|
      ((roles_mask || 0) & 2**ROLES.index(r)).zero?
    end
  end

  def is?(role)
    roles.include?(role.to_s)
  end


end

app/controllers/aplicacions_controller.rb
class AplicacionsController < ApplicationController
  # GET /aplicacions
  # GET /aplicacions.xml
  
  before_filter :authenticate_user!

  def index
    @aplicacions = Aplicacion.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @aplicacions }
    end
  end

  # GET /aplicacions/1
  # GET /aplicacions/1.xml
  def show
    @aplicacion = Aplicacion.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @aplicacion }
    end
  end

  # GET /aplicacions/new
  # GET /aplicacions/new.xml
  def new
    @aplicacion = Aplicacion.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @aplicacion }
    end
  end

  # GET /aplicacions/1/edit
  def edit
    @aplicacion = Aplicacion.find(params[:id])
  end

  # POST /aplicacions
  # POST /aplicacions.xml
  def create
    @aplicacion = Aplicacion.new(params[:aplicacion])

    respond_to do |format|
      if @aplicacion.save
        format.html { redirect_to(@aplicacion, :notice => 'Aplicacion was successfully created.') }
        format.xml  { render :xml => @aplicacion, :status => :created, :location => @aplicacion }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @aplicacion.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /aplicacions/1
  # PUT /aplicacions/1.xml
  def update
    @aplicacion = Aplicacion.find(params[:id])

    respond_to do |format|
      if @aplicacion.update_attributes(params[:aplicacion])
        format.html { redirect_to(@aplicacion, :notice => 'Aplicacion was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @aplicacion.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /aplicacions/1
  # DELETE /aplicacions/1.xml
  def destroy
    @aplicacion = Aplicacion.find(params[:id])
    @aplicacion.destroy

    respond_to do |format|
      format.html { redirect_to(aplicacions_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tesina_controller.rb
class TesinaController < ApplicationController
  def paginaPrincipal
  end

end

app/helpers/aplicacions_helper.rb
module AplicacionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tesina_helper.rb
module TesinaHelper
end

app/views/aplicacions/_form.html.erb
<%= form_for(@aplicacion) do |f| %>
  <% if @aplicacion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aplicacion.errors.count, "error") %> prohibited this aplicacion from being saved:</h2>

      <ul>
      <% @aplicacion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre_camara %><br />
    <%= f.text_field :nombre_camara %>
  </div>
  <div class="field">
    <%= f.label :ip %><br />
    <%= f.text_field :ip %>
  </div>
  <div class="field">
    <%= f.label :ubicacion %><br />
    <%= f.text_field :ubicacion %>
  </div>
  <div class="field">
    <%= f.label :modelo %><br />
    <%= f.text_field :modelo %>
  </div>
  <div class="field">
    <%= f.label :numero_de_serie %><br />
    <%= f.text_field :numero_de_serie %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/aplicacions/edit.html.erb
<h1>Editing aplicacion</h1>

<%= render 'form' %>

<%= link_to 'Show', @aplicacion %> |
<%= link_to 'Back', aplicacions_path %>

app/views/aplicacions/index.html.erb
<h1>Listing aplicacions</h1>

<table>
  <tr>
    <th>Nombre camara</th>
    <th>Ip</th>
    <th>Ubicacion</th>
    <th>Modelo</th>
    <th>Numero de serie</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @aplicacions.each do |aplicacion| %>
  <tr>
    <td><%= aplicacion.nombre_camara %></td>
    <td><%= aplicacion.ip %></td>
    <td><%= aplicacion.ubicacion %></td>
    <td><%= aplicacion.modelo %></td>
    <td><%= aplicacion.numero_de_serie %></td>
    <td><%= link_to 'Show', aplicacion %></td>
    <td><%= link_to 'Edit', edit_aplicacion_path(aplicacion) %></td>
    <td><%= link_to 'Destroy', aplicacion, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<% if current_user.is? :admin %>
  <%= link_to 'New Aplicacion', new_aplicacion_path %>
<% end %>

app/views/aplicacions/new.html.erb
<h1>New aplicacion</h1>

<%= render 'form' %>

<%= link_to 'Back', aplicacions_path %>

app/views/aplicacions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre camara:</b>
  <%= @aplicacion.nombre_camara %>
</p>

<p>
  <b>Ip:</b>
  <%= @aplicacion.ip %>
</p>

<p>
  <b>Ubicacion:</b>
  <%= @aplicacion.ubicacion %>
</p>

<p>
  <b>Modelo:</b>
  <%= @aplicacion.modelo %>
</p>

<p>
  <b>Numero de serie:</b>
  <%= @aplicacion.numero_de_serie %>
</p>


<%= link_to 'Edit', edit_aplicacion_path(@aplicacion) %> |
<%= link_to 'Back', aplicacions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
   <div id="user_nav">  
   <% if user_signed_in? %>  
   Signed in as <%= current_user.email %>. Not you?  
   <%= link_to "Sign out", destroy_user_session_path %>  
   <% else %>  
   <%= link_to "Sign up", new_user_registration_path %> or  
   <%= link_to "Sign in", new_user_session_path %>  
   <% end %>  
   </div>  
<%= yield %>

</body>
</html>

app/views/tesina/paginaPrincipal.html.erb
<HEAD>
<TITLE>Monitor web</TITLE>
</HEAD>


<marquee width="1200" height="90">
<div><font face="JasmineUPC" size="72"><B><I>Monitor Web</I></B></font></div>
</div></marquee>
</div>
<br>

<br><br><br><br><br>
<script type="text/javascript">
var slideimages=new Array()
function slideshowimages()
{
	for (i=0;i<slideshowimages.arguments.length;i++){
	slideimages[i]=new Image();
	slideimages[i].src=slideshowimages.arguments[i];
	}
}

</script>

<img src="/images/img1.bmp" alt="Slideshow Image Script" title="Slideshow Image Script" name="slide" border=0 width=200 height=200 align="right">
<div style="font-size: 10px;color: #dadada;" id="dumdiv">

<script type="text/javascript">
slideshowimages("/images/img1.bmp","/images/img2.bmp","/images/img3.jpg");
var slideshowspeed=1000;
var whichimage=0;
function slideit()
{
	if (!document.images)
		return;
	document.images.slide.src=slideimages[whichimage].src;	
	if (whichimage<slideimages.length-1)
		whichimage++;
	else
		whichimage=0;
	setTimeout("slideit()",slideshowspeed);
}
 slideit();
function ctck()
{
    var sds = document.getElementById("dum");
    if(sds == null){
        alert("Error");
    }
    var sdss = document.getElementById("dumdiv");
    if(sdss == null){
        alert("Error");
    }
}
document.onload="ctck()"; 
</script>
 
<font size="3">
<a href="Int.html"> Introducción</a><br>
<a href="Cap1.html"> Capítulo I</a><br>
<a href="Cap2.html"> Capítulo II</a><br>
<a href="Cap3.html"> Capítulo III</a><br>
<a href="Cap4.html"> Capítulo IV</a><br>
<a href="Ap.html"> Aplicación</a>
</font>

<P><br><br><br><br><br><br><br><br><br><br><br><br><br>
<font face="JasmineUPC" size="4" color="black">
        ESTE PROYECTO CONSISTE EN UN SISTEMA DE SUPERVISIÓN CONTINUO BASADO EN WEB EL CUAL PERMITE 
	ADMINISTRAR Y MONITOREAR TODOS LOS SISTEMAS DE SEGURIDAD QUE SE IMPLEMENTEN 
	MEDIANTE ESTE SISTEMA YA SEA POR INTRANET CORPORATIVA O DESDE INTERNET Y 
	DETECCIÓN DE MOVIMIENTOS EL CUAL PERMITE REDUCIR LA CANTIDAD DE DATOS DE VÍDEO 
	QUE DEBEN ENVIARSE POR LA RED, YA QUE EL ENVÍO DE INFORMACIÓN SOLO SE PRODUCE 
	CUANDO DETECTA UN CAMBIO EN EL PATRÓN DE LA ESCENA QUE PUDIERA SIGNIFICAR UNA 
	ALERTA EN LA SEGURIDAD DE LA ZONA QUE SE ESTA MONITOREANDO.
</font>
</P>